---
title: "RCurl client example"
output: github_document
---

In another R run the following:

```
library("plumber")
r <- plumb("plumber.R")
r$run(port=8000)
```

Then that server can service queries such as the following:

```{r}
library("RCurl")
library("jsonlite")


post_query <- function(method, args) {
  hdr <- c("Content-Type" = "application/x-www-form-urlencoded")
  resp <- postForm(
    paste0("http://localhost:8000/", method),
    .opts=list(httpheader = hdr, 
               postfields = toJSON(args)))
  fromJSON(resp)
}

data <- read.csv("buzz_sample.csv", 
                 stringsAsFactors = FALSE, 
                 strip.white = TRUE)

scores <- post_query("score_data", 
                     list(d = data))
knitr::kable(head(scores))

tab <- table(pred = scores[, 2]>0.5, truth = data$buzz)
knitr::kable(tab)
```

```{r}
i = 27

post_query("score_row_i", 
           list(i = i))

post_query("show_row_i_col", 
           list(i = i, 
                col = "num.displays_01"))

post_query("score_row_i_modified", 
           list(i = i, 
                col = "num.displays_01", 
                newval = 0))

```
