---
output: github_document
---



00442_informalexample_11.1_of_section_11.2.1.R


```{r 00442_informalexample_11.1_of_section_11.2.1.R }
# informalexample 11.1 of section 11.2.1 
# (informalexample 11.1 of section 11.2.1)  : Documentation and deployment : Using R markdown to produce milestone documentation : What is R markdown? 

rmarkdown::render("../Buzz/Buzz_score_example.Rmd", rmarkdown::html_document())



```




00447_example_11.6_of_section_11.3.1.R


```{r 00447_example_11.6_of_section_11.3.1.R }
# example 11.6 of section 11.3.1 
# (example 11.6 of section 11.3.1)  : Documentation and deployment : Using comments and version control for running documentation : Writing effective comments 
# Title: Example code comment 

#    Return the pseudo logarithm of x, which is close to
# sign(x)*log10(abs(x)) for x such that abs(x) is large
# and doesn't "blow up" near zero.  Useful
# for transforming wide-range variables that may be negative
# (like profit/loss).
# See: http://www.win-vector.com/blog
#  /2012/03/modeling-trick-the-signed-pseudo-logarithm/
#    NB: This transform has the undesirable property of making most
# signed distributions appear bimodal around the origin, no matter
# what the underlying distribution really looks like.
# The argument x is assumed be numeric and can be a vector.
pseudoLog10 <- function(x) { asinh(x/2)/log(10) }



```




00448_example_11.7_of_section_11.3.1.R


```{r 00448_example_11.7_of_section_11.3.1.R }
# example 11.7 of section 11.3.1 
# (example 11.7 of section 11.3.1)  : Documentation and deployment : Using comments and version control for running documentation : Writing effective comments 
# Title: Useless comment 

#######################################
# Function: addone
# Author: John Mount
# Version: 1.3.11
# Location: RSource/helperFns/addone.R
# Date: 10/31/13
# Arguments: x
# Purpose: Adds one
#######################################
addone <- function(x) { x + 1 }



```




00449_example_11.8_of_section_11.3.1.R


```{r 00449_example_11.8_of_section_11.3.1.R }
# example 11.8 of section 11.3.1 
# (example 11.8 of section 11.3.1)  : Documentation and deployment : Using comments and version control for running documentation : Writing effective comments 
# Title: Worse than useless comment 

# adds one
addtwo <- function(x) { x + 2 }



```




00462_example_11.17_of_section_11.4.2.R


```{r 00462_example_11.17_of_section_11.4.2.R }
# example 11.17 of section 11.4.2 
# (example 11.17 of section 11.4.2)  : Documentation and deployment : Deploying models : Deploying models by export 
# Title: Exporting the random forest model 

library("randomForest")  	# Note: 1 

lst <- readRDS("../Buzz/../Buzz/thRS500.RDS") 	# Note: 2 
varslist <- lst$varslist
fmodel <- lst$fmodel
buzztest <- lst$buzztest
rm(list = "lst")

extractTrees <- function(rfModel) { 	# Note: 3 
   ei <- function(i) {
      ti <- getTree(rfModel,k=i,labelVar=T)
      ti$nodeid <- 1:dim(ti)[[1]]
      ti$treeid <- i
      ti
   }
   nTrees <- rfModel$ntree
   do.call('rbind',sapply(1:nTrees,ei,simplify=F))
}

write.table(extractTrees(fmodel), 		# Note: 4 
   file='rfmodel.tsv',
   row.names=F,
   sep='\t',
   quote=F)

# Note 1: 
#   Load the random forest library (loading the 
#   workspace doesn’t load the library). 

# Note 2: 
#   Load the saved buzz data (includes the 
#   random forest model). 

# Note 3: 
#   Define a function that joins the tree tables 
#   from the random forest getTree() method into one 
#   large table of trees. 

# Note 4: 
#   Write the table of trees as a tab-separated 
#   values table (easy for other software to 
#   read). 



```


