
/usr/local/bin/R -e 'rmarkdown::render("c01_The_data_science_process.Rmd", rmarkdown::github_document())'
/usr/local/bin/R -e 'rmarkdown::render("c02_Starting_with_R_and_data.Rmd", rmarkdown::github_document())'
/usr/local/bin/R -e 'rmarkdown::render("c03_Exploring_data.Rmd", rmarkdown::github_document())'
/usr/local/bin/R -e 'rmarkdown::render("c04_Managing_data.Rmd", rmarkdown::github_document())'
/usr/local/bin/R -e 'rmarkdown::render("c05_Data_Engineering_and_Data_Shaping.Rmd", rmarkdown::github_document())'
/usr/local/bin/R -e 'rmarkdown::render("c06_Choosing_and_evaluating_models.Rmd", rmarkdown::github_document())'
/usr/local/bin/R -e 'rmarkdown::render("c07_Linear_and_logistic_regression.Rmd", rmarkdown::github_document())'
/usr/local/bin/R -e 'rmarkdown::render("c08_Advanced_Data_Preparation.Rmd", rmarkdown::github_document())'
/usr/local/bin/R -e 'rmarkdown::render("c09_Unsupervised_methods.Rmd", rmarkdown::github_document())'
/usr/local/bin/R -e 'rmarkdown::render("c10_Exploring_advanced_methods.Rmd", rmarkdown::github_document())'
/usr/local/bin/R -e 'rmarkdown::render("c11_Documentation_and_deployment.Rmd", rmarkdown::github_document())'
/usr/local/bin/R -e 'rmarkdown::render("x0A_Working_with_R_and_other_tools.Rmd", rmarkdown::github_document())'
/usr/local/bin/R -e 'rmarkdown::render("x0B_Important_statistical_concepts.Rmd", rmarkdown::github_document())'

