---
title: "render_examples.Rmd"
output: github_document
---

```{r}
library("rmarkdown")
```

```{r}
date()
rmarkdown::render("c01_The_data_science_process.Rmd", github_document())
date()
```

```{r}
date()
rmarkdown::render("c02_Starting_with_R_and_data.Rmd", github_document())
date()
```

```{r}
date()
rmarkdown::render("c03_Exploring_data.Rmd", github_document())
date()
```

```{r}
date()
rmarkdown::render("c04_Managing_data.Rmd", github_document())
```

```{r}
date()
rmarkdown::render("c05_Data_Engineering_and_Data_Shaping.Rmd", github_document())
```

```{r}
date()
rmarkdown::render("c06_Choosing_and_evaluating_models.Rmd", github_document())
```

```{r}
date()
rmarkdown::render("c07_Linear_and_logistic_regression.Rmd", github_document())
date()
```

```{r}
date()
rmarkdown::render("c08_Advanced_Data_Preparation.Rmd", github_document())
date()
```

```{r}
date()
rmarkdown::render("c09_Unsupervised_methods.Rmd", github_document())
date()
```

```{r}
date()
rmarkdown::render("c10_Exploring_advanced_methods.Rmd", github_document())
date()
```

```{r}
date()
rmarkdown::render("c11_Documentation_and_deployment.Rmd", github_document())
date()
```

```{r}
date()
rmarkdown::render("x0A_Working_with_R_and_other_tools.Rmd", github_document())
date()
```

```{r}
date()
rmarkdown::render("x0B_Important_statistical_concepts.Rmd", github_document())
date()
```

